apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: kuard
  name: kuard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: kuard
  type: LoadBalancer
status:
  loadBalancer: {}
