#!/bin/bash 
source <(kubectl completion bash)

LATEST=1.11.2-gke.18
CLUSTER=boonchu-cluster-1
PROJECT=boonchu-project

h=`date|cut -d" " -f4|cut -d: -f1`
if [ \( $h -gt 7 -a $h -lt 20 \) ]; then
        REGION=us-west2
	ZONE=us-west2-a
elif [ \( $h -ge 0 -a $h -le 7 \) -o $h -ge 20  ]; then
        REGION=asia-southeast1
	ZONE=asia-southeast1-a
else
	echo 'Has problem with reading time.'
	exit 1
fi

# default: gcloud container clusters create boonchu-cluster-1 --num-nodes 2
# machine-type: gcloud compute machine-types list: "n1-standard-1"
# image-type: gcloud container get-server-config: "COS_CONTAINERD"

MACHINE=n1-standard-1
IMAGE=COS_CONTAINERD

gcloud config set project ${PROJECT}
gcloud config set compute/region ${REGION}
gcloud config set compute/zone ${ZONE}

gcloud config get-value compute/zone 
gcloud config get-value compute/region

export KUBECONFIG=$(PWD)/boonchu-cluster-1.conf
